#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Oct 29 13:52:36 2018

@author: guru

Normalize kappa0 and kappaL data: for the curves reported in M. Schrade, see if
kappa_L over kappa_0 is the same for each curve
"""

import numpy as np


fileFit = "/Users/guru/Documents/PDscattering/datafiles/FitDisp_Hf.csv"
fileDebye = "/Users/guru/Documents/PDscattering/datafiles/Debye_Hf.csv"
fileDebye_2 = "/Users/guru/Documents/PDscattering/datafiles/Debye_max_Hf.csv"

cFit, kFit = np.genfromtext(fileFit, dtype = 'float', delimiter = ',')
    

