#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed Jun 27 09:23:36 2018

@author: guru

PD mass and strain fluctuation scattering

"""

from PDmassfluct import bfz, puc
import numpy as np




